config/routes.rb
Rails.application.routes.draw do
  resources :menu_items
  resources :fooditems
  get 'welcome/index'
  get 'contact' => 'welcome#contact'
  get 'menu' => 'welcome#menu'

  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fooditem.rb
class Fooditem < ApplicationRecord
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
end

app/models/section.rb
class Section
	def self.all
		%w(Breakfast Lunch Dinner Drinks All)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fooditems_controller.rb
class FooditemsController < ApplicationController
  before_action :set_fooditem, only: [:show, :edit, :update, :destroy]

  # GET /fooditems
  # GET /fooditems.json
  def index
    @fooditems = Fooditem.all
  end

  # GET /fooditems/1
  # GET /fooditems/1.json
  def show
  end

  # GET /fooditems/new
  def new
    @fooditem = Fooditem.new
  end

  # GET /fooditems/1/edit
  def edit
  end

  # POST /fooditems
  # POST /fooditems.json
  def create
    @fooditem = Fooditem.new(fooditem_params)

    respond_to do |format|
      if @fooditem.save
        format.html { redirect_to @fooditem, notice: 'Fooditem was successfully created.' }
        format.json { render :show, status: :created, location: @fooditem }
      else
        format.html { render :new }
        format.json { render json: @fooditem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fooditems/1
  # PATCH/PUT /fooditems/1.json
  def update
    respond_to do |format|
      if @fooditem.update(fooditem_params)
        format.html { redirect_to @fooditem, notice: 'Fooditem was successfully updated.' }
        format.json { render :show, status: :ok, location: @fooditem }
      else
        format.html { render :edit }
        format.json { render json: @fooditem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fooditems/1
  # DELETE /fooditems/1.json
  def destroy
    @fooditem.destroy
    respond_to do |format|
      format.html { redirect_to fooditems_url, notice: 'Fooditem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fooditem
      @fooditem = Fooditem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fooditem_params
      params.require(:fooditem).permit(:name, :description, :price, :section, :url)
    end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = MenuItem.all
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully created.' }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1
  # PATCH/PUT /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: 'Menu item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_item_params
      params.require(:menu_item).permit(:name, :description, :price, :section, :url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def menu
	if params[:section]
			if params[:section] != 'All'
				@menu_items =  MenuItem.where section: params[:section]
			else
				@menu_items = MenuItem.all
			end
		else
			@menu_items = MenuItem.all
		end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fooditems_helper.rb
module FooditemsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fooditems/_form.html.erb
<%= form_with(model: fooditem, local: true) do |form| %>
  <% if fooditem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fooditem.errors.count, "error") %> prohibited this fooditem from being saved:</h2>

      <ul>
      <% fooditem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :section %>
    <%= form.text_field :section %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fooditems/edit.html.erb
<h1>Editing Fooditem</h1>

<%= render 'form', fooditem: @fooditem %>

<%= link_to 'Show', @fooditem %> |
<%= link_to 'Back', fooditems_path %>

app/views/fooditems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fooditems</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fooditems.each do |fooditem| %>
      <tr>
        <td><%= fooditem.name %></td>
        <td><%= fooditem.description %></td>
        <td><%= fooditem.price %></td>
        <td><%= fooditem.section %></td>
        <td><%= fooditem.url %></td>
        <td><%= link_to 'Show', fooditem %></td>
        <td><%= link_to 'Edit', edit_fooditem_path(fooditem) %></td>
        <td><%= link_to 'Destroy', fooditem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fooditem', new_fooditem_path %>

app/views/fooditems/new.html.erb
<h1>New Fooditem</h1>

<%= render 'form', fooditem: @fooditem %>

<%= link_to 'Back', fooditems_path %>

app/views/fooditems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fooditem.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fooditem.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @fooditem.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @fooditem.section %>
</p>

<p>
  <strong>Url:</strong>
  <%= @fooditem.url %>
</p>

<%= link_to 'Edit', edit_fooditem_path(@fooditem) %> |
<%= link_to 'Back', fooditems_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>W1Restaurant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item, local: true) do |form| %>
  <% if menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
      <% menu_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :section %>
    <%= form.text_field :section %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_items/edit.html.erb
<h1>Editing Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Show', @menu_item %> |
<%= link_to 'Back', menu_items_path %>

app/views/menu_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menu Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.name %></td>
        <td><%= menu_item.description %></td>
        <td><%= menu_item.price %></td>
        <td><%= menu_item.section %></td>
        <td><%= menu_item.url %></td>
        <td><%= link_to 'Show', menu_item %></td>
        <td><%= link_to 'Edit', edit_menu_item_path(menu_item) %></td>
        <td><%= link_to 'Destroy', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu Item', new_menu_item_path %>

app/views/menu_items/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Back', menu_items_path %>

app/views/menu_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @menu_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu_item.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @menu_item.section %>
</p>

<p>
  <strong>Url:</strong>
  <%= @menu_item.url %>
</p>

<%= link_to 'Edit', edit_menu_item_path(@menu_item) %> |
<%= link_to 'Back', menu_items_path %>

app/views/welcome/contact.html.erb
<div class='row'>
	<div class='col-1'></div>
	<div class='col-8'><h1>My Restaurant</h1></div>
	
</div>
<div class='row'>
	<div class='col-1'></div>
	<div class='col-4'>
		<address>9B/3A Nguyễn Thị Nhỏ <br>
			Phường 15<br>
			Quận 11<br>
			Hồ Chí Minh<br>
			Vietnam<br>
			+84 123456789<br>
			Open: 7:30AM–10:30PM
		</address>
	</div>
	<div>
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1959.7750448307474!2d106.65243353892149!3d10.76911569943165!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752eeab232908f%3A0x18d6d63d57c51a1b!2zOUIvM0EgTmd1eeG7hW4gVGjhu4sgTmjhu48sIFBoxrDhu51uZyAxNSwgUXXhuq1uIDExLCBI4buTIENow60gTWluaCwgVmlldG5hbQ!5e0!3m2!1sen!2s!4v1535847184444" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>

app/views/welcome/index.html.erb
<div class='row'>
	<div class='col-1'></div>
	<div class='col-10'>
		<div class="jumbotron">
		  <h1 class="display-3">Welcome to My Restaurant</h1>
		  <hr class="m-y-2">
		  <p class="lead">
		    <%= link_to "Menu", menu_path ,class: "btn btn-primary btn-lg" %>
		    <%= link_to "Contact Us", contact_path ,class: "btn btn-secondary btn-lg" %>
  		</p>
		</div>
	</div>
</div>

app/views/welcome/menu.html.erb
<div class='row'>
	<div class='col-1'></div>
	<div class='col-10'>
		<h1>Here is our Menu</h1>

		<% Section.all.each do |section| %>
			<div class="btn-group" role="group" aria-label="Basic example"> 
			 	 <%= link_to section, menu_path(section: section), class: 'btn btn-outline-primary btn-sm' %>
			</div>
		<% end %>

		<% @menu_items.each do |menu_item| %>
			<div class="card">
					<div class="card-header"><%= menu_item.name%></div>
			</div> 
			<div class="card-block">
				<div class="row">
					<div class="col-xs-12 col-md-8">
						<%= image_tag menu_item.url %>
					</div>
					<div class="col-xs-6 col-md-4">
						<p><strong>Description:</strong> <%= menu_item.description %></p>
						<p><strong>Price:</strong> <%= menu_item.price %> VND</p>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>